
import type { Metadata } from "next";
import { getServerSession } from "@/server/auth";
import { redirect } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function DashborardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  if (!session?.user) {
    redirect("/api/auth/signin");
  }

  return (
    <div>
      <nav>
        <Button variant="ghost">
          <Avatar>
            <AvatarImage src={session.user.image!}></AvatarImage>
            <AvatarFallback style={{ color: "black" }}>
              {session.user.name?.substring(0, 2)}
            </AvatarFallback>
          </Avatar>
        </Button>
      </nav>
      <main>{children}</main>
    </div>
  );
}
