
import type { Metadata } from "next";
import 'asecretman/build/index.css'

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashborardLayout({
  children
}:{children:React.ReactNode}) {
  return (      
   <div>
        <main>{children}</main>
      
   </div>
  );
}
